export default {
  Intro: 'IntroScreen',
  Login: 'LoginScreen',
  Register: 'RegisterScreen',
  MainTab: 'MainTabScreen',
  Home: 'HomeScreen',
  ListSchedule: 'ListTripScreen',
  Explore: 'ExploreScreen',
  Personal: 'PersonalScreen',
  Destination: 'DestinationScreen',
  CreateSchedule: 'CreateScheduleScreen',
  DetailSchedule: 'DetailScheduleScreen',
  MapView: 'MapViewScreen',
  UpdatePersonal: 'UpdatePersonalScreen',
  About: 'AboutScreen',
  Setting: 'SettingScreen',
  PostedReview: 'PostedReviewScreen',
  SavedReview: 'SavedReviewScreen',
  MyWallet: 'MyWalletScreen',
  EditSchedule: 'EditScheduleScreen',
  DetailReview: 'DetailReviewScreen',
  CreateReview: 'CreateReviewScreen',
  Search: 'SearchScreen',
  EditDestination: 'EditDestinationScreen',
};
